# Generated by Django 6.0.1 on 2026-02-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('planned', 'Not Chosen Yet'), ('watching', 'Watching'), ('watched', 'Watched')], default='planned', max_length=10),
        ),
    ]
